// Code generated by goctl. DO NOT EDIT.
// Source: ucenter.proto

package server

import (
	"context"

	"ucenter_srv/internal/logic"
	"ucenter_srv/internal/svc"
	"ucenter_srv/pb/ucenter"
)

type UcenterServer struct {
	svcCtx *svc.ServiceContext
	ucenter.UnimplementedUcenterServer
}

func NewUcenterServer(svcCtx *svc.ServiceContext) *UcenterServer {
	return &UcenterServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *UcenterServer) RegisterByPhone(ctx context.Context, in *ucenter.RegReq) (*ucenter.RegRes, error) {
	l := logic.NewRegisterByPhoneLogic(ctx, s.svcCtx)
	return l.RegisterByPhone(in)
}

func (s *UcenterServer) SendCode(ctx context.Context, in *ucenter.CodeReq) (*ucenter.NoRes, error) {
	l := logic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

// 会员查找
func (s *UcenterServer) FindMemberById(ctx context.Context, in *ucenter.MemberReq) (*ucenter.MemberInfo, error) {
	l := logic.NewFindMemberByIdLogic(ctx, s.svcCtx)
	return l.FindMemberById(in)
}

// 会员列表
func (s *UcenterServer) FindMembers(ctx context.Context, in *ucenter.MembersReq) (*ucenter.MembersRes, error) {
	l := logic.NewFindMembersLogic(ctx, s.svcCtx)
	return l.FindMembers(in)
}

// 登录
func (s *UcenterServer) Login(ctx context.Context, in *ucenter.LoginReq) (*ucenter.LoginRes, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UcenterServer) FindWalletBySymbol(ctx context.Context, in *ucenter.AssetReq) (*ucenter.MemberWallet, error) {
	l := logic.NewFindWalletBySymbolLogic(ctx, s.svcCtx)
	return l.FindWalletBySymbol(in)
}
