// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"goods_srv/internal/logic"
	"goods_srv/internal/svc"
	"goods_srv/pb/goods"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

// -----------------------goods-----------------------
func (s *GoodsServer) AddGoods(ctx context.Context, in *goods.AddGoodsReq) (*goods.AddGoodsResp, error) {
	l := logic.NewAddGoodsLogic(ctx, s.svcCtx)
	return l.AddGoods(in)
}

func (s *GoodsServer) UpdateGoods(ctx context.Context, in *goods.UpdateGoodsReq) (*goods.UpdateGoodsResp, error) {
	l := logic.NewUpdateGoodsLogic(ctx, s.svcCtx)
	return l.UpdateGoods(in)
}

func (s *GoodsServer) DelGoods(ctx context.Context, in *goods.DelGoodsReq) (*goods.DelGoodsResp, error) {
	l := logic.NewDelGoodsLogic(ctx, s.svcCtx)
	return l.DelGoods(in)
}

func (s *GoodsServer) GetGoodsById(ctx context.Context, in *goods.GetGoodsByIdReq) (*goods.GetGoodsByIdResp, error) {
	l := logic.NewGetGoodsByIdLogic(ctx, s.svcCtx)
	return l.GetGoodsById(in)
}

func (s *GoodsServer) SearchGoods(ctx context.Context, in *goods.SearchGoodsReq) (*goods.SearchGoodsResp, error) {
	l := logic.NewSearchGoodsLogic(ctx, s.svcCtx)
	return l.SearchGoods(in)
}
