// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	asset "ucenter_api/internal/handler/asset"
	user "ucenter_api/internal/handler/user"
	"ucenter_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendcode",
				Handler: user.SendCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/findone",
				Handler: user.FindOneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/jwtcheck",
				Handler: user.JWTCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/uc"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/wallet",
					Handler: asset.WalletHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/asset"),
	)
}
